"""Added Student model

Revision ID: 1f81c550b49c
Revises: e4739cd1a8ee
Create Date: 2025-03-09 21:26:29.567457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f81c550b49c'
down_revision = 'e4739cd1a8ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
