"""Added Student model

Revision ID: e4739cd1a8ee
Revises: 9b481b55450c
Create Date: 2025-03-09 21:25:33.756096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4739cd1a8ee'
down_revision = '9b481b55450c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
